# AWS codeDeploy
version: 0.0
os: linux

# 전체 파일을 EC2 서버의 destination 폴더에 저장하겠다.
files:
  - source: / 
    destination: /home/ubuntu/Theraphy-HTP
  file_exists_behavior: OVERWITE

permissions:
  - object: /home/ubuntu/Theraphy-HTP
    owner: ubuntu
    group: ubuntu

# codeDeploy 수명 중 하나인 AfterInstall 발생 시 코드에서 deploy.sh를 수행하겠다는 이벤트
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu