version: '3'
services:
  nginx_proxy:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend-node
      - backend-flask
    restart: always
    container_name: nginx_proxy
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      # host PC의 ./nginx/nginx.conf로 container의 /etc/nginx/nginx.conf를 대체

  frontend:
    build: ./frontend
    expose:
      - "80"
      - "3000"
      - "8080"
    container_name: frontend
    # react-scripts 3.4.1 이상에서 발생하는 exited with code 0 에러 해결법
    # https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true
    tty: true

  backend-node:
    build: ./backend-node
    expose:
      - "3001"
    container_name: backend-node
    environment:
      # 콘테이너 내 환경변수를 정의
      - NODE_PATH

  backend-flask:
    build: ./backend-flask
    expose:
      - "5000"
    container_name: backend-flask

# docker rm -f $(docker ps -aq)
# docker rmi $(docker images -q)

# docker-compose build --no-cache && docker-compose up -d
