version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # react-scripts 3.4.1 이상에서 발생하는 exited with code 0 에러 해결법
    # https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true
    tty: true
  backend-node:
    build: ./backend-node
    ports:
      - "3001:3001"
  backend-flask:
    build: ./backend-flask
    ports:
      - "5000:5000"
