version: '3'
services:
  nginx_proxy:
    image: nginx:1.18.0
    ports:
      # expose container ports. 
      # - "3000:3000"
      # - "3001:3001"
      # - "5000:5000"
      - "80:80"
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      # host PC의 ./nginx/nginx.conf로 container의 /etc/nginx/nginx.conf를 대체

  frontend:
    depends_on:
      # service간 종속성을 나타낸다
      - nginx_proxy
    build: ./frontend
    # react-scripts 3.4.1 이상에서 발생하는 exited with code 0 에러 해결법
    # https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true
    tty: true

  backend-node:
    depends_on:
      - nginx_proxy
    build: ./backend-node
    environment:
      # 콘테이너 내 환경변수를 정의
      - NODE_PATH

  backend-flask:
    depends_on:
      - nginx_proxy
    build: ./backend-flask

# docker rm -f $(docker ps -aq)
# docker rmi $(docker images -q)
