FROM python:3.6.12

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

WORKDIR /app/keras-retinanet

RUN python setup.py install

RUN python setup.py build_ext --inplace

WORKDIR /app

# container 실행 시 발생하는 libGL.so.1: cannot open shared object file: No such file or directory 에러에 대한 대처
RUN apt-get update

RUN apt-get -y install libgl1-mesa-glx

ENTRYPOINT python Inference_model.py

# EXPOSE 5000

# ENTRYPOINT gunicorn Inference_model:app -b 0.0.0.0:5000 --timeout=10

# POST /predict
# port :5000
