# workflow 이름 명시
name: Docker Image CI

# workflow의 trigger 설정
on:
  push: # push event
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # DOCKER_IMAGE: ghcr.io/{Repository author}/{Repository name} # 예를 들면, ghcr.io/dolphago/github-follow-unfollow
  # VERSION: ${{ github.sha }}
  PROJECT_NAME: cicd_project
  BUCKET_NAME: theraphy-cicd-bucket
  CODE_DEPLOY_APP_NAME: cicdapp
  DEPLOYMENT_GROUP_NAME: cicdapp_deploy

permissions:
  id-token: write
  contents: read

jobs:
  build: # job의 이름
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildxc
      id: buildx
      uses: docker/setup-buildx-action@v1

    # - name: Run Docker-compose #
      # run: docker-compose up -d # script
      
    # - name: Build and push
    #   id: docker_build
    #   uses: docker/build-push-action@v2
    #   with:
    #     builder: ${{ steps.buildx.outputs.name }}
    #     push: ${{ github.event_name != 'pull_request' }}
    #     tags: ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}

    - name: Make Zip File
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

    - name: Code Deploy
      run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip

    # - name: Build the Docker image e
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
