# workflow 이름 명시
name: gh-actions-AWS-EC2-theraphy-CICD

# workflow의 trigger 설정
on:
  push: # push event
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_NAME: theraphy-htp-project
  BUCKET_NAME: theraphy-htp-bucket
  CODE_DEPLOY_APP_NAME: theraphy-CICD-codeDeploy
  DEPLOYMENT_GROUP_NAME: cicdRole_codeDeploy

jobs:
  build: # job의 이름
    runs-on: ubuntu-latest

    steps:
    # worflow에서 $GITHUB_WORKSPACE에 접근이 가능하게끔 해주는 action
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        lfs: 'true'
    
    - name: checkoutLFS
      uses: actions/checkout@v3
      run: git lfs pull

    # $GITHUB_SHA는 Github Actions에서 제공하는 환경변수.
    - name: Make Zip File
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    # using AWS CLI at run
    - name: Delete all files on S3
      run: aws s3 rm s3://$BUCKET_NAME/ --recursive --include "*"

    - name: Upload .zip file to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

    - name: Code Deploy
      run: >
        aws deploy create-deployment 
        --application-name $CODE_DEPLOY_APP_NAME
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name $DEPLOYMENT_GROUP_NAME
        --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip